# Generated by Django 4.2.1 on 2023-05-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_accounts_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('recipient_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_acc', to='customers.accounts')),
                ('sender_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_acc', to='customers.accounts')),
            ],
        ),
    ]
