# Generated by Django 4.2.1 on 2023-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
